-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnDpnrcFhLxfQZsql
UKkWNMmmX1heO4Cd+uVpqbiAlNmgCgYIKoZIzj0DAQehRANCAAQCDv0dWWTLPWlZ
19CEQLokUD2JXUFOazG4x+NUig5rlwS0CyzN3AEamfI2NgGa4ZXXHJOPNhzc6G+/
8PI4O0XR
-----END PRIVATE KEY-----